APPEARANCE_THEMES = {
        "Night Watercolor": {
            "bg": "#171a22",
            "panel": "#1d2230",
            "panel2": "#252b3a",
            "line": "#3b4558",
            "text": "#e7edf7",
            "muted": "#aab6c8",
            "editor": "#121722",
            "accent": "#82c7d9",
            "select": "#5e8fc5",
            "highlight": "#f0d38a",
            "highlight_text": "#141821",
            "comment": "#94c9a9",
            "keyword": "#9ec7ff",
            "string": "#e8b6b0",
            "number": "#c4d99b",
        },
        "Night Lavender Wash": {
            "bg": "#1b1923",
            "panel": "#232032",
            "panel2": "#2d2940",
            "line": "#463f5d",
            "text": "#eee9f8",
            "muted": "#beb4d3",
            "editor": "#15131d",
            "accent": "#c8a4e8",
            "select": "#816dad",
            "highlight": "#e8cf91",
            "highlight_text": "#17131d",
            "comment": "#9fc8ad",
            "keyword": "#b9c8ff",
            "string": "#efb5c7",
            "number": "#d4d7a2",
        },
        "Day Watercolor": {
            "bg": "#f7f1e8",
            "panel": "#fff9ef",
            "panel2": "#f1eadf",
            "line": "#dccfc1",
            "text": "#34353a",
            "muted": "#7b7d86",
            "editor": "#fffdf8",
            "accent": "#7db8be",
            "select": "#9ec9d2",
            "highlight": "#f5d783",
            "highlight_text": "#34312a",
            "comment": "#6f9f7b",
            "keyword": "#5a84b8",
            "string": "#b97b72",
            "number": "#7c995e",
        },
        "Day Rose Mist": {
            "bg": "#fbf3f4",
            "panel": "#fffafa",
            "panel2": "#f5e8eb",
            "line": "#e2cfd5",
            "text": "#3b3338",
            "muted": "#83747c",
            "editor": "#fffdfd",
            "accent": "#d99bb1",
            "select": "#e7b7c8",
            "highlight": "#f2d68c",
            "highlight_text": "#332b2f",
            "comment": "#78a386",
            "keyword": "#7d8cc4",
            "string": "#b9788b",
            "number": "#879b61",
        },
        "Day Sage Wash": {
            "bg": "#f2f6ef",
            "panel": "#fbfff8",
            "panel2": "#e9f0e4",
            "line": "#cfdbc8",
            "text": "#30382f",
            "muted": "#73806e",
            "editor": "#fefff9",
            "accent": "#91bfa3",
            "select": "#abd2b8",
            "highlight": "#ecd98f",
            "highlight_text": "#303427",
            "comment": "#6a9a76",
            "keyword": "#5c87aa",
            "string": "#aa7e76",
            "number": "#79935b",
        },
        "Neon Rose Circuit": {
            "bg": "#0D0912",
            "panel": "#17101F",
            "panel2": "#24172F",
            "editor": "#110C18",
            "text": "#F6EAF7",
            "muted": "#A78DAF",
            "line": "#3C2848",
            "accent": "#FF4FCB",
            "select": "#6F2C68",
            "highlight": "#FFD166",
            "highlight_text": "#1B1018",
            "comment": "#89D6A3",
            "keyword": "#FF8BE4",
            "string": "#F5B1D7",
            "number": "#FFD166",
        },
        "Nuclear Terminal": {
            "bg": "#070B08",
            "panel": "#0D150F",
            "panel2": "#142119",
            "editor": "#09100B",
            "text": "#E8F5E9",
            "muted": "#829B87",
            "line": "#263C2B",
            "accent": "#62FF72",
            "select": "#245C31",
            "highlight": "#D7FF3F",
            "highlight_text": "#081008",
            "comment": "#7CBF7F",
            "keyword": "#9DFFAA",
            "string": "#C7F7C9",
            "number": "#D7FF3F",
        },
        "Soft Vintage Studio": {
            "bg": "#F4EDE3",
            "panel": "#E8DCCF",
            "panel2": "#FFF8EE",
            "editor": "#F9F2E8",
            "text": "#493F3B",
            "muted": "#8C7D76",
            "line": "#C9B8AA",
            "accent": "#C97878",
            "select": "#D8C7E8",
            "highlight": "#F3D58A",
            "highlight_text": "#3F3834",
            "comment": "#7B8F6A",
            "keyword": "#7D6D9E",
            "string": "#A86868",
            "number": "#8E805D",
        },
        "Precision Machine": {
            "bg": "#15181C",
            "panel": "#20252A",
            "panel2": "#2B3137",
            "editor": "#191D21",
            "text": "#E5E9EC",
            "muted": "#8D969E",
            "line": "#3A4249",
            "accent": "#42A5F5",
            "select": "#294F6B",
            "highlight": "#F2B84B",
            "highlight_text": "#101419",
            "comment": "#8CA891",
            "keyword": "#74B9FF",
            "string": "#D69A73",
            "number": "#F2B84B",
        },
        "Retro Computing": {
            "bg": "#211B17",
            "panel": "#302820",
            "panel2": "#44372A",
            "editor": "#271F1A",
            "text": "#F2E6C9",
            "muted": "#A99B7C",
            "line": "#5C4B38",
            "accent": "#E66B3D",
            "select": "#72533C",
            "highlight": "#E7C547",
            "highlight_text": "#241D18",
            "comment": "#9CAB70",
            "keyword": "#E6A85C",
            "string": "#E69A7A",
            "number": "#E7C547",
        },
    }
