def context_settings():
    return {
        "key": "context",
        "title": "Context",
        "advanced_only": True,
        "description": "Tune how much code and session context the app gathers before sending. Open advanced controls only for precise retrieval tuning.",
        "sections": [
            {
                "title": "Context Retrieval",
                "subsections": [
                    {
                        "title": "How much context to gather",
                        "fields": [
                            {
                                "key": "context.include_selected_snippets",
                                "label": "Attach checked snippets",
                                "type": "bool",
                                "default": True,
                                "description": "Send checked snippet cards as explicit context.",
                                "used": True,
                            },
                            {
                                "key": "context.preview_retrieval_enabled",
                                "label": "Preview retrieved context while typing",
                                "type": "bool",
                                "default": True,
                                "description": "Run a background dry retrieval when draft context changes, so Context Inspector estimates the final context before Send.",
                                "used": True,
                            },
                            {
                                "key": "context.preview_task_quality_enabled",
                                "label": "Score task clarity while typing",
                                "type": "bool",
                                "default": True,
                                "description": "Ask the configured model for a tiny task-clarity score. Failures are ignored.",
                                "used": True,
                            },
                        ],
                    },
                    {
                        "title": "Budget and inspection",
                        "fields": [
                            {
                                "key": "context.reserve_output_tokens",
                                "label": "Reserve answer space",
                                "type": "int",
                                "default": 1600,
                                "description": "Estimated response space reserved when judging whether context fits the selected window.",
                                "used": True,
                            },
                            {
                                "key": "context.warning_threshold_percent",
                                "label": "Warn near context limit",
                                "type": "int",
                                "default": 85,
                                "description": "Usage percentage where Context Inspector starts warning that the prompt is getting full.",
                                "used": True,
                            },
                            {
                                "key": "context.create_audit_card",
                                "label": "Create final context audit card",
                                "type": "bool",
                                "default": True,
                                "description": "Add a generated card with final budget and quality details after Send.",
                                "used": True,
                            },
                        ],
                    },
                    {
                        "title": "Advanced: Send behavior",
                        "advanced": True,
                        "fields": [
                            {
                                "key": "context.max_attached_chars",
                                "label": "Max attached context chars",
                                "type": "int",
                                "default": 0,
                                "description": "Optional character cap for attached context. 0 means uncapped.",
                                "used": True,
                            },
                            {
                                "key": "context.optimization_enabled",
                                "label": "Optimize context before send",
                                "type": "bool",
                                "default": True,
                                "description": "Measure and lightly optimize assembled context before sending.",
                                "used": True,
                            },
                            {
                                "key": "context.remove_duplicate_sections",
                                "label": "Remove duplicate context sections",
                                "type": "bool",
                                "default": True,
                                "description": "Drop exact duplicate context sections while preserving explicit unique context.",
                                "used": True,
                            },
                            {
                                "key": "context.allow_auto_compaction",
                                "label": "Allow automatic context compaction",
                                "type": "bool",
                                "default": False,
                                "description": "Permit the optimizer to apply the attached-character cap automatically.",
                                "used": True,
                            },
                            {
                                "key": "context.preview_task_quality_min_chars",
                                "label": "Task clarity minimum chars",
                                "type": "int",
                                "default": 20,
                                "description": "Minimum draft length before requesting the optional LLM task-clarity score.",
                                "used": True,
                            },
                        ],
                    },
                    {
                        "title": "Advanced: RepoLens engine",
                        "advanced": True,
                        "fields": [
                            {"key": "repolens.chat.enabled", "label": "Use RepoLens on Send", "type": "bool", "default": True, "description": "Retrieve RepoLens context before sending chat messages.", "used": True},
                            {"key": "repolens.chat.create_card", "label": "Create RepoLens context card on Send", "type": "bool", "default": True, "description": "Add retrieved RepoLens context as a visible snippet card.", "used": True},
                            {"key": "repolens.chat.update_before_retrieval", "label": "Update index before Send retrieval", "type": "bool", "default": False, "description": "Run RepoLens update before retrieval. Disable when background indexing is enough.", "used": True},
                            {"key": "repolens.chat.update_lite", "label": "Use lite update before Send", "type": "bool", "default": True, "description": "When updating before Send, use RepoLens --lite.", "used": True},
                            {"key": "repolens.context.include_tree", "label": "Include reduced file tree", "type": "bool", "default": True, "description": "Ask RepoLens to include a reduced file tree.", "used": True},
                            {"key": "repolens.context.include_types", "label": "Include related types", "type": "bool", "default": True, "description": "Ask RepoLens to include related type definitions.", "used": True},
                            {"key": "repolens.context.partial_fallback", "label": "Use partial fallback", "type": "bool", "default": True, "description": "Retry with partial symbol matching when exact context finds no code items.", "used": True},
                            {"key": "repolens.context.budget_chars", "label": "RepoLens character budget", "type": "int", "default": 60000, "description": "Character budget passed to RepoLens context retrieval.", "used": True},
                            {"key": "repolens.context.max_symbols", "label": "Max symbols per retrieval", "type": "int", "default": 12, "description": "Maximum extracted symbols sent to RepoLens.", "used": True},
                            {"key": "repolens.context.basic", "label": "Use basic context mode", "type": "bool", "default": False, "description": "Ask RepoLens for a smaller basic package.", "used": True},
                            {"key": "repolens.context.situated", "label": "Include situated descriptions", "type": "bool", "default": False, "description": "Prefix snippets with stored/fallback descriptions.", "used": True},
                            {"key": "repolens.context.signals_query", "label": "Signals query", "type": "string", "default": "", "description": "Optional query for imported build/test/terminal/chat signals.", "used": True},
                            {"key": "repolens.context.grow_enabled", "label": "Allow bounded query growth", "type": "bool", "default": False, "description": "Allow RepoLens --grow to index only listed grow files when a symbol is missing.", "used": True},
                            {"key": "repolens.context.grow_files", "label": "Grow files", "type": "string", "default": "", "description": "Comma-separated files RepoLens may parse for --grow.", "used": True},
                        ],
                    },
                    {
                        "title": "Advanced: Smart retrieval",
                        "advanced": True,
                        "fields": [
                            {"key": "smart_context.enabled", "label": "Use Smart Context on Send", "type": "bool", "default": True, "description": "Build a focused RepoLens package from snippets and file references.", "used": True},
                            {"key": "smart_context.create_step_cards", "label": "Create step cards", "type": "bool", "default": False, "description": "Add visible cards for intermediate retrieval steps.", "used": True},
                            {"key": "smart_context.create_final_card", "label": "Create final context card", "type": "bool", "default": True, "description": "Add the final retrieved context as a checked clipboard card.", "used": True},
                            {"key": "smart_context.max_exact_symbols", "label": "Max exact symbols", "type": "int", "default": 32, "description": "Maximum strong symbols kept from planning.", "used": True},
                            {"key": "smart_context.max_patterns", "label": "Max naming patterns", "type": "int", "default": 12, "description": "Maximum naming patterns used to discover related code.", "used": True},
                            {"key": "smart_context.max_pattern_results", "label": "Pattern results", "type": "int", "default": 5, "description": "Maximum RepoLens search hits kept per naming pattern.", "used": True},
                            {"key": "smart_context.max_final_symbols", "label": "Max final symbols", "type": "int", "default": 48, "description": "Maximum validated symbols sent to RepoLens context.", "used": True},
                            {"key": "smart_context.max_context_items", "label": "Max context items", "type": "int", "default": 50, "description": "Maximum pruned RepoLens context items retained.", "used": True},
                            {"key": "smart_context.include_source_ranges", "label": "Include selected source ranges", "type": "bool", "default": True, "description": "Attach exact selected file ranges with line numbers.", "used": True},
                            {"key": "smart_context.source_range_padding_lines", "label": "Source range padding lines", "type": "int", "default": 4, "description": "Lines included before and after selected ranges.", "used": True},
                            {"key": "smart_context.max_source_range_chars", "label": "Max source range chars", "type": "int", "default": 24000, "description": "Maximum source-range characters in final context.", "used": True},
                            {"key": "smart_context.include_resolution_evidence", "label": "Include resolution evidence", "type": "bool", "default": True, "description": "Add validated RepoLens search hits with symbols/files/lines.", "used": True},
                            {"key": "smart_context.include_reference_inventory", "label": "Include reference inventory", "type": "bool", "default": True, "description": "Add compact per-snippet extracted reference lists.", "used": True},
                            {"key": "smart_context.enable_chain_expansion", "label": "Follow related code chains", "type": "bool", "default": True, "description": "Walk from retrieved declarations into initialized members, types, and related references.", "used": True},
                            {"key": "smart_context.exclude_library_paths", "label": "Exclude library/package paths", "type": "bool", "default": True, "description": "Drop context from packages, vendor, build, bin, obj, and similar paths.", "used": True},
                            {"key": "smart_context.include_tree", "label": "Include RepoLens tree", "type": "bool", "default": False, "description": "Include RepoLens reduced file tree in Smart Context.", "used": True},
                            {"key": "smart_context.include_warnings", "label": "Include RepoLens warnings", "type": "bool", "default": False, "description": "Include RepoLens warnings in final Smart Context.", "used": True},
                        ],
                    },
                    {
                        "title": "Advanced: Intent depths",
                        "advanced": True,
                        "fields": [
                            {"key": "repolens.depth.explain", "label": "Explain depth", "type": "int", "default": 1, "description": "RepoLens depth for explanation prompts.", "used": True},
                            {"key": "repolens.depth.fix", "label": "Fix depth", "type": "int", "default": 2, "description": "RepoLens depth for bug/error prompts.", "used": True},
                            {"key": "repolens.depth.change", "label": "Change depth", "type": "int", "default": 2, "description": "RepoLens depth for generation/refactoring prompts.", "used": True},
                            {"key": "repolens.depth.review", "label": "Review depth", "type": "int", "default": 2, "description": "RepoLens depth for review/testing/security prompts.", "used": True},
                            {"key": "repolens.depth.write", "label": "Write depth", "type": "int", "default": 1, "description": "RepoLens depth for writing/documentation prompts.", "used": True},
                            {"key": "repolens.depth.research", "label": "Research depth", "type": "int", "default": 3, "description": "RepoLens depth for research/impact/architecture prompts.", "used": True},
                            {"key": "smart_context.min_depth", "label": "Smart Context minimum depth", "type": "int", "default": 1, "description": "Lower bound for Smart Context depth.", "used": True},
                            {"key": "smart_context.max_depth", "label": "Smart Context maximum depth", "type": "int", "default": 3, "description": "Upper bound for Smart Context depth.", "used": True},
                        ],
                    },
                ],
            },
        ],
    }
