from src.services.llamacpp import DEFAULT_LLAMA_CONTEXT_SIZE, LLAMA_MODELS_DIR, LLAMA_UI_DIR, default_model_path, llama_server_executable


def model_provider_settings():
    return {
        "key": "model_provider",
        "title": "Model & Provider",
        "description": "Select the model source, context window, and provider credentials.",
        "sections": [
            {
                "title": "Provider",
                "subsections": [
                    {
                        "title": "Where responses come from",
                        "fields": [
                            {
                                "key": "api.use_local_api",
                                "label": "Use local Llama.cpp server",
                                "type": "bool",
                                "default": True,
                                "description": "When checked, chat uses the local OpenAI-compatible server. When unchecked, chat uses OpenRouter.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.ctx_size",
                                "label": "Context window",
                                "type": "int",
                                "default": DEFAULT_LLAMA_CONTEXT_SIZE,
                                "description": "The prompt window available to the selected local model. Larger values allow broader context if the model/server supports them.",
                                "used": True,
                            },
                        ],
                    },
                    {
                        "title": "Local model",
                        "fields": [
                            {
                                "key": "llamacpp.model_path",
                                "label": "Model path",
                                "type": "string",
                                "default": str(default_model_path()),
                                "description": "GGUF model passed to llama-server with -m.",
                                "used": True,
                            },
                            {
                                "key": "api.default_base_url",
                                "label": "Local server URL",
                                "type": "string",
                                "default": "http://localhost:8080",
                                "description": "OpenAI-compatible local API base URL.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.reload_model",
                                "label": "Reload local model",
                                "type": "action",
                                "action": "reload_llamacpp_model",
                                "button_text": "Reload model with new configuration",
                                "description": "Restarts the local llama-server using the current local model settings.",
                                "used": True,
                            },
                        ],
                    },
                    {
                        "title": "OpenRouter",
                        "fields": [
                            {
                                "key": "openrouter.model",
                                "label": "OpenRouter model",
                                "type": "string",
                                "default": "openrouter/free",
                                "description": "Model name used when local API is disabled.",
                                "used": True,
                            },
                            {
                                "key": "openrouter.api_key",
                                "label": "OpenRouter API key",
                                "type": "string",
                                "default": "",
                                "description": "Stored in settings/session files. Leave blank if you do not use OpenRouter.",
                                "used": True,
                            },
                        ],
                    },
                    {
                        "title": "Advanced provider settings",
                        "advanced": True,
                        "fields": [
                            {
                                "key": "llamacpp.auto_launch",
                                "label": "Launch Llama.cpp on startup",
                                "type": "bool",
                                "default": True,
                                "description": "Start llama-server automatically after choosing a session.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.executable_path",
                                "label": "llama-server path",
                                "type": "string",
                                "default": str(llama_server_executable()),
                                "description": "Path to llama-server.exe or llama-server.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.ui_path",
                                "label": "Web UI folder",
                                "type": "string",
                                "default": str(LLAMA_UI_DIR),
                                "description": "Folder passed to llama-server with --path.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.models_dir",
                                "label": "Models folder",
                                "type": "string",
                                "default": str(LLAMA_MODELS_DIR),
                                "description": "Folder where GGUF models are stored.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.host",
                                "label": "Host",
                                "type": "string",
                                "default": "0.0.0.0",
                                "description": "Host passed to llama-server with --host.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.port",
                                "label": "Port",
                                "type": "int",
                                "default": 8080,
                                "description": "Port passed to llama-server with --port.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.n_gpu_layers",
                                "label": "GPU layers",
                                "type": "string",
                                "default": "0",
                                "description": "Value passed to --n-gpu-layers. Use all or a number.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.parallel",
                                "label": "Parallel slots",
                                "type": "int",
                                "default": 1,
                                "description": "Value passed to llama-server with --parallel.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.flash_attn",
                                "label": "Flash attention",
                                "type": "choice",
                                "choices": ["on", "off", "auto"],
                                "default": "off",
                                "description": "Value passed to llama-server with --flash-attn.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.fit",
                                "label": "Fit context",
                                "type": "choice",
                                "choices": ["off", "on"],
                                "default": "off",
                                "description": "Value passed to llama-server with --fit.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.n_cpu_moe",
                                "label": "CPU MoE experts",
                                "type": "int",
                                "default": 0,
                                "description": "Optional value for -n-cpu-moe / -ncmoe. 0 leaves it unset.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.reasoning",
                                "label": "Server reasoning mode",
                                "type": "choice",
                                "choices": ["on", "off", ""],
                                "default": "",
                                "description": "Optional llama-server --reasoning value.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.cache_type_k",
                                "label": "Cache type K",
                                "type": "string",
                                "default": "",
                                "description": "Optional --cache-type-k value, for example q8_0.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.cache_type_v",
                                "label": "Cache type V",
                                "type": "string",
                                "default": "",
                                "description": "Optional --cache-type-v value, for example q8_0.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.cache_type_k_draft",
                                "label": "Draft cache type K",
                                "type": "string",
                                "default": "",
                                "description": "Optional --cache-type-k-draft value for speculative decoding.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.cache_type_v_draft",
                                "label": "Draft cache type V",
                                "type": "string",
                                "default": "",
                                "description": "Optional --cache-type-v-draft value for speculative decoding.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.spec_type",
                                "label": "Speculative decoding type",
                                "type": "string",
                                "default": "",
                                "description": "Optional --spec-type value, for example draft-mtp.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.spec_draft_n_max",
                                "label": "Spec draft max tokens",
                                "type": "int",
                                "default": 0,
                                "description": "Optional --spec-draft-n-max value. 0 leaves it unset.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.temperature",
                                "label": "Server temperature",
                                "type": "string",
                                "default": "",
                                "description": "Optional llama-server --temp value. Leave blank to use chat request temperature.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.top_p",
                                "label": "Server top P",
                                "type": "string",
                                "default": "",
                                "description": "Optional llama-server --top-p value.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.top_k",
                                "label": "Server top K",
                                "type": "int",
                                "default": 0,
                                "description": "Optional llama-server --top-k value. 0 leaves it unset.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.min_p",
                                "label": "Server min P",
                                "type": "string",
                                "default": "",
                                "description": "Optional llama-server --min-p value.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.presence_penalty",
                                "label": "Server presence penalty",
                                "type": "string",
                                "default": "",
                                "description": "Optional llama-server --presence-penalty value.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.repeat_penalty",
                                "label": "Server repeat penalty",
                                "type": "string",
                                "default": "",
                                "description": "Optional llama-server --repeat-penalty value.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.verbosity",
                                "label": "Verbosity level",
                                "type": "int",
                                "default": 0,
                                "description": "Optional -lv value. 0 leaves it unset.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.cache_idle_slots",
                                "label": "Cache idle slots",
                                "type": "bool",
                                "default": False,
                                "description": "Pass --cache-idle-slots to llama-server.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.kv_unified",
                                "label": "Unified KV cache",
                                "type": "bool",
                                "default": False,
                                "description": "Pass --kv-unified to llama-server.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.alias",
                                "label": "Model alias",
                                "type": "string",
                                "default": "",
                                "description": "Optional -a alias shown by llama-server.",
                                "used": True,
                            },
                            {
                                "key": "llamacpp.extra_args",
                                "label": "Extra llama-server args",
                                "type": "string",
                                "default": "",
                                "description": "Additional llama-server flags.",
                                "used": True,
                            },
                            {
                                "key": "api.chat_completions_path",
                                "label": "Chat completions path",
                                "type": "string",
                                "default": "/v1/chat/completions",
                                "description": "Appended to base URLs that do not include a chat endpoint.",
                                "used": True,
                            },
                            {
                                "key": "api.request_timeout_seconds",
                                "label": "Request timeout seconds",
                                "type": "int",
                                "default": 180,
                                "description": "Timeout for local and remote API calls.",
                                "used": True,
                            },
                            {
                                "key": "openrouter.endpoint",
                                "label": "OpenRouter endpoint",
                                "type": "string",
                                "default": "https://openrouter.ai/api/v1/chat/completions",
                                "description": "OpenRouter chat completions endpoint.",
                                "used": True,
                            },
                            {
                                "key": "openrouter.app_title",
                                "label": "OpenRouter app title",
                                "type": "string",
                                "default": "codeSnippets",
                                "description": "Sent as OpenRouter X-Title metadata.",
                                "used": True,
                            },
                        ],
                    },
                ],
            },
        ],
    }
