# Auto-generated CodeSnippets profile. Keep PROFILE as a Python literal.
PROFILE = {'description': 'Flat settings mirror. Edit values, then restart the app or reopen Settings.',
 'format': 1,
 'name': 'appearance',
 'settings': {'appearance.colors.accent': '',
              'appearance.colors.bg': '',
              'appearance.colors.comment': '',
              'appearance.colors.editor': '',
              'appearance.colors.highlight': '',
              'appearance.colors.highlight_text': '',
              'appearance.colors.keyword': '',
              'appearance.colors.line': '',
              'appearance.colors.muted': '',
              'appearance.colors.number': '',
              'appearance.colors.panel': '',
              'appearance.colors.panel2': '',
              'appearance.colors.select': '',
              'appearance.colors.string': '',
              'appearance.colors.text': '',
              'appearance.text.base': 9,
              'appearance.text.code': 12,
              'appearance.text.small': 11,
              'appearance.text.title': 10,
              'appearance.theme': 'Precision Machine'}}
