# Auto-generated CodeSnippets profile. Keep PROFILE as a Python literal.
PROFILE = {'description': 'Flat settings mirror. Edit values, then restart the app or reopen Settings.',
 'format': 1,
 'name': 'llamacpp',
 'settings': {'llamacpp.alias': '',
              'llamacpp.auto_launch': True,
              'llamacpp.cache_idle_slots': False,
              'llamacpp.cache_type_k': '',
              'llamacpp.cache_type_k_draft': '',
              'llamacpp.cache_type_v': '',
              'llamacpp.cache_type_v_draft': '',
              'llamacpp.ctx_size': 8000,
              'llamacpp.executable_path': 'C:\\Users\\djc2t\\Desktop\\no\\src\\assets\\LlamaCPP\\llama-server.exe',
              'llamacpp.extra_args': '',
              'llamacpp.fit': 'off',
              'llamacpp.flash_attn': 'off',
              'llamacpp.host': '0.0.0.0',
              'llamacpp.kv_unified': False,
              'llamacpp.min_p': '',
              'llamacpp.model_path': '.',
              'llamacpp.models_dir': 'C:\\Users\\djc2t\\Desktop\\no\\src\\assets\\llmmodels',
              'llamacpp.n_cpu_moe': 0,
              'llamacpp.n_gpu_layers': '0',
              'llamacpp.parallel': 1,
              'llamacpp.port': 8080,
              'llamacpp.presence_penalty': '',
              'llamacpp.reasoning': '',
              'llamacpp.repeat_penalty': '',
              'llamacpp.spec_draft_n_max': 0,
              'llamacpp.spec_type': '',
              'llamacpp.temperature': '',
              'llamacpp.top_k': 0,
              'llamacpp.top_p': '',
              'llamacpp.ui_path': 'C:\\Users\\djc2t\\Desktop\\no\\src\\assets\\LlamaCPP\\ui',
              'llamacpp.verbosity': 0}}
